name: Continuous Integration

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu
        make install-dev
    - name: Lint and format check
      run: |
        make lint
    - name: Static type testing and unittest
      run: |
        make test